fetch_devto_articles:
  cron: "*/30 * * * *" # execute every 30 minutes
  class: "FetchDevtoArticlesJob"
  queue: news

run_5_minutes_checks_job:
  cron: "*/5 * * * *"
  class: "RunChecksJob"
  queue: blazer
  args: "5 minutes"

run_1_hour_checks_job:
  cron: "0 * * * *"
  class: "RunChecksJob"
  queue: blazer
  args: "1 hour"

run_1_day_checks_job:
  cron: "30 7 * * *"
  class: "RunChecksJob"
  queue: blazer
  args: "1 day"

send_failing_checks:
  cron: "0 8 * * *"
  class: "SendFailingChecksJob"
  queue: blazer
