# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tech-talent-accelerator-dashboard

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://techtalentaccelerator-hrbad8e9hzegbddb.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_b9a13441d6624e16b888a7c4998388f4 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_3f8e999c8c2845e4a08099413a3299c0 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: techtalentaccelerator-hrbad8e9hzegbddb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b9a13441d6624e16b888a7c4998388f4 }}/dashboard:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech-talent-accelerator-dashboard'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_fc21a38029be45b88fc0721c43df226f }}
          images: 'techtalentaccelerator-hrbad8e9hzegbddb.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b9a13441d6624e16b888a7c4998388f4 }}/dashboard:${{ github.sha }}'